language: node_js
node_js: node
env:
- NODE_ENV=test
services:
  - postgresql
before_script:
  # - psql -U postgres -c 'CREATE DATABASE "noteful-test";'
  # - psql -U postgres  -c "CREATE ROLE dev WITH PASSWORD 'dev';" 
  - psql -U travis -f ./db/noteful.4.sql