language: node_js
node_js: node
env:
- NODE_ENV=test
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE "noteful-test";'
  - psql -U postgres  -c "CREATE USER dev WITH PASSWORD 'dev';" 
  - psql -U dev -f ./db/noteful.4.sql