language: node_js
node_js: node
env:
- NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE "noteful-test";'
  # - psql -U postgres  -c "CREATE USER dev WITH PASSWORD 'dev';" 
  # - psql -U postgres  -c "CREATE ROlE travis WITH PASSWORD 'dev';" 
  - psql -U postgres -f ./db/noteful.4.sql